/*   
    Copyright (C) 2009 Galaktika Corporation ZAO

    This file is a part of Ranet.UILibrary.Olap
 
    Ranet.UILibrary.Olap is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
      
    You should have received a copy of the GNU General Public License
    along with Ranet.UILibrary.Olap.  If not, see
  	<http://www.gnu.org/licenses/> 
  
    If GPL v.3 is not suitable for your products or company,
    Galaktika Corp provides Ranet.UILibrary.Olap under a flexible commercial license
    designed to meet your specific usage and distribution requirements.
    If you have already obtained a commercial license from Galaktika Corp,
    you can use this file under those license terms.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranet.AgOlap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ranet.AgOlap.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is unavailable.
        /// </summary>
        internal static string Clipboard_ClipboardUnavailable {
            get {
                return ResourceManager.GetString("Clipboard_ClipboardUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy the text.
        /// </summary>
        internal static string Clipboard_UnableCopy {
            get {
                return ResourceManager.GetString("Clipboard_UnableCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection_PropertyDesc {
            get {
                return ResourceManager.GetString("Connection_PropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ContextCmd_Copy {
            get {
                return ResourceManager.GetString("ContextCmd_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ContextCmd_Cut {
            get {
                return ResourceManager.GetString("ContextCmd_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextCmd_Delete {
            get {
                return ResourceManager.GetString("ContextCmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ContextCmd_Paste {
            get {
                return ResourceManager.GetString("ContextCmd_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ContextCmd_SelectAll {
            get {
                return ResourceManager.GetString("ContextCmd_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy value.
        /// </summary>
        internal static string ContextMenu_CopyValue {
            get {
                return ResourceManager.GetString("ContextMenu_CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom properties.
        /// </summary>
        internal static string ContextMenu_CustomProperties {
            get {
                return ResourceManager.GetString("ContextMenu_CustomProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery value.
        /// </summary>
        internal static string ContextMenu_DeliveryValue {
            get {
                return ResourceManager.GetString("ContextMenu_DeliveryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ContextMenu_Properties {
            get {
                return ResourceManager.GetString("ContextMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MDX.
        /// </summary>
        internal static string ContextMenu_ShowMDX {
            get {
                return ResourceManager.GetString("ContextMenu_ShowMDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; for control is not initialized..
        /// </summary>
        internal static string ControlPropertyNotInitialized_Message {
            get {
                return ResourceManager.GetString("ControlPropertyNotInitialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not initialized: {0}.
        /// </summary>
        internal static string ControlSettingsNotInitialized_Message {
            get {
                return ResourceManager.GetString("ControlSettingsNotInitialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard_ToolTip {
            get {
                return ResourceManager.GetString("CopyToClipboard_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Browser.
        /// </summary>
        internal static string CubeBrowserControl_Name {
            get {
                return ResourceManager.GetString("CubeBrowserControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube choice control.
        /// </summary>
        internal static string CubeChoiceControl_Name {
            get {
                return ResourceManager.GetString("CubeChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Name.
        /// </summary>
        internal static string CubeName_PropertyDesc {
            get {
                return ResourceManager.GetString("CubeName_PropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom properties....
        /// </summary>
        internal static string CustomPropertiesDialog_Caption {
            get {
                return ResourceManager.GetString("CustomPropertiesDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDX Query (2 Axes).
        /// </summary>
        internal static string DataSourceInfo_MovedAxes {
            get {
                return ResourceManager.GetString("DataSourceInfo_MovedAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show parsed query.
        /// </summary>
        internal static string DataSourceInfo_ShowParsedQuery {
            get {
                return ResourceManager.GetString("DataSourceInfo_ShowParsedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show parsed script.
        /// </summary>
        internal static string DataSourceInfo_ShowParsedScript {
            get {
                return ResourceManager.GetString("DataSourceInfo_ShowParsedScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source information....
        /// </summary>
        internal static string DataSourceInfoDialog_Caption {
            get {
                return ResourceManager.GetString("DataSourceInfoDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date choice.
        /// </summary>
        internal static string DateChoice_Caption {
            get {
                return ResourceManager.GetString("DateChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date choice control.
        /// </summary>
        internal static string DateChoiceControl_Name {
            get {
                return ResourceManager.GetString("DateChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogButton_Cancel {
            get {
                return ResourceManager.GetString("DialogButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogButton_Ok {
            get {
                return ResourceManager.GetString("DialogButton_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension choice control.
        /// </summary>
        internal static string DimensionChoiceControl_Name {
            get {
                return ResourceManager.GetString("DimensionChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension unique name.
        /// </summary>
        internal static string DimensionUniqueName_PropertyDesc {
            get {
                return ResourceManager.GetString("DimensionUniqueName_PropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Operand.
        /// </summary>
        internal static string Filter_AddOperand {
            get {
                return ResourceManager.GetString("Filter_AddOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Operation.
        /// </summary>
        internal static string Filter_AddOperation {
            get {
                return ResourceManager.GetString("Filter_AddOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin with.
        /// </summary>
        internal static string Filter_BeginWith {
            get {
                return ResourceManager.GetString("Filter_BeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Filter_Contains {
            get {
                return ResourceManager.GetString("Filter_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string Filter_Equal {
            get {
                return ResourceManager.GetString("Filter_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string Filter_Label_And {
            get {
                return ResourceManager.GetString("Filter_Label_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string Filter_Label_By {
            get {
                return ResourceManager.GetString("Filter_Label_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Filter_Target_Items {
            get {
                return ResourceManager.GetString("Filter_Target_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Filter_Target_Percent {
            get {
                return ResourceManager.GetString("Filter_Target_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string Filter_Target_Sum {
            get {
                return ResourceManager.GetString("Filter_Target_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Filter_Type_Bottom {
            get {
                return ResourceManager.GetString("Filter_Type_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Filter_Type_Top {
            get {
                return ResourceManager.GetString("Filter_Type_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter building.
        /// </summary>
        internal static string FilterBuilder_Caption {
            get {
                return ResourceManager.GetString("FilterBuilder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterControl_Caption {
            get {
                return ResourceManager.GetString("FilterControl_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter settings:.
        /// </summary>
        internal static string FilterControl_Label_FilterSettings {
            get {
                return ResourceManager.GetString("FilterControl_Label_FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter type:.
        /// </summary>
        internal static string FilterControl_Label_FilterType {
            get {
                return ResourceManager.GetString("FilterControl_Label_FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy choice control.
        /// </summary>
        internal static string HierarchyChoiceControl_Name {
            get {
                return ResourceManager.GetString("HierarchyChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy unique name.
        /// </summary>
        internal static string HierarchyUniqueName_PropertyDesc {
            get {
                return ResourceManager.GetString("HierarchyUniqueName_PropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI choice.
        /// </summary>
        internal static string KPIChoice_Caption {
            get {
                return ResourceManager.GetString("KPIChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI choice control.
        /// </summary>
        internal static string KpiChoiceControl_Name {
            get {
                return ResourceManager.GetString("KpiChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin with.
        /// </summary>
        internal static string LabelFilter_BeginWith {
            get {
                return ResourceManager.GetString("LabelFilter_BeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string LabelFilter_Contain {
            get {
                return ResourceManager.GetString("LabelFilter_Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End with.
        /// </summary>
        internal static string LabelFilter_EndWith {
            get {
                return ResourceManager.GetString("LabelFilter_EndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Filter.
        /// </summary>
        internal static string LabelFilter_Name {
            get {
                return ResourceManager.GetString("LabelFilter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not begin with.
        /// </summary>
        internal static string LabelFilter_NotBeginWith {
            get {
                return ResourceManager.GetString("LabelFilter_NotBeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        internal static string LabelFilter_NotContain {
            get {
                return ResourceManager.GetString("LabelFilter_NotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not end with.
        /// </summary>
        internal static string LabelFilter_NotEndWith {
            get {
                return ResourceManager.GetString("LabelFilter_NotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level choice.
        /// </summary>
        internal static string LevelChoice_Caption {
            get {
                return ResourceManager.GetString("LevelChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level choice control.
        /// </summary>
        internal static string LevelChoiceControl_Name {
            get {
                return ResourceManager.GetString("LevelChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From.
        /// </summary>
        internal static string LoadDialog_Caption {
            get {
                return ResourceManager.GetString("LoadDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string MdxDesigner_ColumnsArea_Caption {
            get {
                return ResourceManager.GetString("MdxDesigner_ColumnsArea_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Filter.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_CancelFilter {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_CancelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Filter.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_ChangeFilter {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_ChangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_MoveDown {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Columns.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_MoveToColumnsArea {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_MoveToColumnsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Filters.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_MoveToFiltersArea {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_MoveToFiltersArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Rows.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_MoveToRowsArea {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_MoveToRowsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_MoveUp {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Field.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_RemoveField {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_RemoveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top N.
        /// </summary>
        internal static string MdxDesigner_ContextMenu_TopFilter {
            get {
                return ResourceManager.GetString("MdxDesigner_ContextMenu_TopFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Metadata.
        /// </summary>
        internal static string MdxDesigner_CubeMetadata {
            get {
                return ResourceManager.GetString("MdxDesigner_CubeMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string MdxDesigner_DataArea_Caption {
            get {
                return ResourceManager.GetString("MdxDesigner_DataArea_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute MDX query.
        /// </summary>
        internal static string MdxDesigner_ExecuteQuery {
            get {
                return ResourceManager.GetString("MdxDesigner_ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export query layout settings.
        /// </summary>
        internal static string MdxDesigner_ExportLayout_ToolTip {
            get {
                return ResourceManager.GetString("MdxDesigner_ExportLayout_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string MdxDesigner_FilterArea_Caption {
            get {
                return ResourceManager.GetString("MdxDesigner_FilterArea_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import query layout settings.
        /// </summary>
        internal static string MdxDesigner_ImportLayout_ToolTip {
            get {
                return ResourceManager.GetString("MdxDesigner_ImportLayout_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDX Query.
        /// </summary>
        internal static string MdxDesigner_MdxQuery {
            get {
                return ResourceManager.GetString("MdxDesigner_MdxQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query result.
        /// </summary>
        internal static string MdxDesigner_QueryResult {
            get {
                return ResourceManager.GetString("MdxDesigner_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string MdxDesigner_RowsArea_Caption {
            get {
                return ResourceManager.GetString("MdxDesigner_RowsArea_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run MDX query automatic.
        /// </summary>
        internal static string MdxDesigner_RunQueryAutomatic {
            get {
                return ResourceManager.GetString("MdxDesigner_RunQueryAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide MDX query.
        /// </summary>
        internal static string MdxDesigner_ShowQuery_ToolTip {
            get {
                return ResourceManager.GetString("MdxDesigner_ShowQuery_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide query designer.
        /// </summary>
        internal static string MdxDesigner_ShowQueryDesigner_ToolTip {
            get {
                return ResourceManager.GetString("MdxDesigner_ShowQueryDesigner_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string MdxDesigner_ValuesNode_Caption {
            get {
                return ResourceManager.GetString("MdxDesigner_ValuesNode_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDX Query.
        /// </summary>
        internal static string MDXQuery {
            get {
                return ResourceManager.GetString("MDXQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure choice.
        /// </summary>
        internal static string MeasureChoice_Caption {
            get {
                return ResourceManager.GetString("MeasureChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure choice control.
        /// </summary>
        internal static string MeasureChoiceControl_Name {
            get {
                return ResourceManager.GetString("MeasureChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Group.
        /// </summary>
        internal static string MeasureGroup {
            get {
                return ResourceManager.GetString("MeasureGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All&gt;.
        /// </summary>
        internal static string MeasureGroup_All {
            get {
                return ResourceManager.GetString("MeasureGroup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members choice.
        /// </summary>
        internal static string MemberChoice_Caption {
            get {
                return ResourceManager.GetString("MemberChoice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string MemberChoice_ClearSelection_ToolTip {
            get {
                return ResourceManager.GetString("MemberChoice_ClearSelection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All ....
        /// </summary>
        internal static string MemberChoice_LoadAll {
            get {
                return ResourceManager.GetString("MemberChoice_LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Next ....
        /// </summary>
        internal static string MemberChoice_LoadNext {
            get {
                return ResourceManager.GetString("MemberChoice_LoadNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members found: .
        /// </summary>
        internal static string MemberChoice_MembersFound {
            get {
                return ResourceManager.GetString("MemberChoice_MembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members selected: .
        /// </summary>
        internal static string MemberChoice_MembersSelected {
            get {
                return ResourceManager.GetString("MemberChoice_MembersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Multi Select&gt;.
        /// </summary>
        internal static string MemberChoice_MultiSelect {
            get {
                return ResourceManager.GetString("MemberChoice_MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MemberChoice_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("MemberChoice_Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string MemberChoice_Selected {
            get {
                return ResourceManager.GetString("MemberChoice_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Custom Member Properties.
        /// </summary>
        internal static string MemberChoice_ShowMemberProperties_ToolTip {
            get {
                return ResourceManager.GetString("MemberChoice_ShowMemberProperties_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member choice control.
        /// </summary>
        internal static string MemberChoiceControl_Name {
            get {
                return ResourceManager.GetString("MemberChoiceControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error....
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning....
        /// </summary>
        internal static string MessageBox_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string ObjectDescriptionControl_Caption {
            get {
                return ResourceManager.GetString("ObjectDescriptionControl_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ObjectDescriptionControl_Description {
            get {
                return ResourceManager.GetString("ObjectDescriptionControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ObjectDescriptionControl_Name {
            get {
                return ResourceManager.GetString("ObjectDescriptionControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Object is damaged. Loading impossible..
        /// </summary>
        internal static string ObjectLoadDialog_ContentError_Message {
            get {
                return ResourceManager.GetString("ObjectLoadDialog_ContentError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name is empty. Please fill field &apos;Name&apos;..
        /// </summary>
        internal static string ObjectSaveDialog_NameIsEmpty_Message {
            get {
                return ResourceManager.GetString("ObjectSaveDialog_NameIsEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with such name already exists. Do you want to replace it?.
        /// </summary>
        internal static string ObjectSaveDialog_Replace_Message {
            get {
                return ResourceManager.GetString("ObjectSaveDialog_Replace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Backward (Ctrl+Left).
        /// </summary>
        internal static string PivotGrid_BackButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_BackButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore table data in initial state or state before recalculation?.
        /// </summary>
        internal static string PivotGrid_CancelEditButton_Question {
            get {
                return ResourceManager.GetString("PivotGrid_CancelEditButton_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore table data in initial state or state before recalculation.
        /// </summary>
        internal static string PivotGrid_CancelEditButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_CancelEditButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That command cannot be use on multiple selections..
        /// </summary>
        internal static string PivotGrid_CellsCopyAreaError {
            get {
                return ResourceManager.GetString("PivotGrid_CellsCopyAreaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string PivotGrid_Collapse {
            get {
                return ResourceManager.GetString("PivotGrid_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Shift+Minus).
        /// </summary>
        internal static string PivotGrid_Columns_Collapse_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Columns_Collapse_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Shift+Enter).
        /// </summary>
        internal static string PivotGrid_Columns_Drilldown_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Columns_Drilldown_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Shift+Plus).
        /// </summary>
        internal static string PivotGrid_Columns_Expand_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Columns_Expand_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string PivotGrid_ConfirmEditButton_Caption {
            get {
                return ResourceManager.GetString("PivotGrid_ConfirmEditButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate table data with current changes?.
        /// </summary>
        internal static string PivotGrid_ConfirmEditButton_Question {
            get {
                return ResourceManager.GetString("PivotGrid_ConfirmEditButton_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate table data with current changes.
        /// </summary>
        internal static string PivotGrid_ConfirmEditButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ConfirmEditButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected cells to Clipboard.
        /// </summary>
        internal static string PivotGrid_CopyToClipboardButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_CopyToClipboardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom properties for member not found. Possible member is calculated..
        /// </summary>
        internal static string PivotGrid_CustomProperties_NotFound {
            get {
                return ResourceManager.GetString("PivotGrid_CustomProperties_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrillDown.
        /// </summary>
        internal static string PivotGrid_DrillDown {
            get {
                return ResourceManager.GetString("PivotGrid_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off Editing Mode.
        /// </summary>
        internal static string PivotGrid_EditButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_EditButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string PivotGrid_Expand {
            get {
                return ResourceManager.GetString("PivotGrid_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Microsoft Excel.
        /// </summary>
        internal static string PivotGrid_ExportToExcelButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ExportToExcelButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate Forward (Ctrl+Right).
        /// </summary>
        internal static string PivotGrid_ForwardButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ForwardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Focused Cell.
        /// </summary>
        internal static string PivotGrid_GoToFocusedCellButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_GoToFocusedCellButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Empty Columns.
        /// </summary>
        internal static string PivotGrid_HideEmptyColumnsButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_HideEmptyColumnsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Empty Rows.
        /// </summary>
        internal static string PivotGrid_HideEmptyRowsButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_HideEmptyRowsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide members and cells hints.
        /// </summary>
        internal static string PivotGrid_HideHintsButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_HideHintsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste cells from Clipboard.
        /// </summary>
        internal static string PivotGrid_PasteFromClipboardButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_PasteFromClipboardButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string PivotGrid_RefreshButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_RefreshButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default size for columns and rows members.
        /// </summary>
        internal static string PivotGrid_RestoreDefaultSize_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_RestoreDefaultSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate axes.
        /// </summary>
        internal static string PivotGrid_RotateAxesButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_RotateAxesButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Minus).
        /// </summary>
        internal static string PivotGrid_Rows_Collapse_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Rows_Collapse_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Enter).
        /// </summary>
        internal static string PivotGrid_Rows_Drilldown_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Rows_Drilldown_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Plus).
        /// </summary>
        internal static string PivotGrid_Rows_Expand_ShortCut {
            get {
                return ResourceManager.GetString("PivotGrid_Rows_Expand_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation requires the recalculation given with provision for contributed change. 
        ///
        ///Please, recalculate data or cancel changes..
        /// </summary>
        internal static string PivotGrid_SaveCachedChanges {
            get {
                return ResourceManager.GetString("PivotGrid_SaveCachedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate To Begin (Ctrl+Shift+Left).
        /// </summary>
        internal static string PivotGrid_ToBeginButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ToBeginButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate To End (Ctrl+Shift+Right).
        /// </summary>
        internal static string PivotGrid_ToEndButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ToEndButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use remitted recalculation.
        /// </summary>
        internal static string PivotGrid_UseChangesCasheButton_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_UseChangesCasheButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string PivotGrid_ZoomingControl_ToolTip {
            get {
                return ResourceManager.GetString("PivotGrid_ZoomingControl_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot grid.
        /// </summary>
        internal static string PivotGridControl_Name {
            get {
                return ResourceManager.GetString("PivotGridControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        internal static string PropertiesDialog_Caption {
            get {
                return ResourceManager.GetString("PropertiesDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PropertiesList_PropertyColumn {
            get {
                return ResourceManager.GetString("PropertiesList_PropertyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string PropertiesList_ValueColumn {
            get {
                return ResourceManager.GetString("PropertiesList_ValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAsDialog_Caption {
            get {
                return ResourceManager.GetString("SaveAsDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xls Files (.xls)|*.xls.
        /// </summary>
        internal static string SaveDialog_Filter_XlsFiles {
            get {
                return ResourceManager.GetString("SaveDialog_Filter_XlsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Files (.xml)|*.xml.
        /// </summary>
        internal static string SaveDialog_Filter_XmlFiles {
            get {
                return ResourceManager.GetString("SaveDialog_Filter_XmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Explorer control.
        /// </summary>
        internal static string ServerExplorerControl_Name {
            get {
                return ResourceManager.GetString("ServerExplorerControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube: {0}.
        /// </summary>
        internal static string Tooltip_Cube {
            get {
                return ResourceManager.GetString("Tooltip_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension: {0}.
        /// </summary>
        internal static string Tooltip_Dimension {
            get {
                return ResourceManager.GetString("Tooltip_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy: {0}.
        /// </summary>
        internal static string Tooltip_Hierarchy {
            get {
                return ResourceManager.GetString("Tooltip_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {0}.
        /// </summary>
        internal static string Tooltip_Level {
            get {
                return ResourceManager.GetString("Tooltip_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top N.
        /// </summary>
        internal static string TopFilter_Name {
            get {
                return ResourceManager.GetString("TopFilter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Top N&apos; Filter.
        /// </summary>
        internal static string TopFilterDialog_Caption {
            get {
                return ResourceManager.GetString("TopFilterDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        internal static string TreeNode_ErrorLoadingData {
            get {
                return ResourceManager.GetString("TreeNode_ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Script.
        /// </summary>
        internal static string UpdateScript {
            get {
                return ResourceManager.GetString("UpdateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update script.
        /// </summary>
        internal static string UpdateScript_PropertyDesc {
            get {
                return ResourceManager.GetString("UpdateScript_PropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string ValueCopyControl_Accessibility {
            get {
                return ResourceManager.GetString("ValueCopyControl_Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates:.
        /// </summary>
        internal static string ValueCopyControl_Coordinates {
            get {
                return ResourceManager.GetString("ValueCopyControl_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string ValueCopyControl_CoordinateState_Disabled {
            get {
                return ResourceManager.GetString("ValueCopyControl_CoordinateState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access.
        /// </summary>
        internal static string ValueCopyControl_CoordinateState_Enabled {
            get {
                return ResourceManager.GetString("ValueCopyControl_CoordinateState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly.
        /// </summary>
        internal static string ValueCopyControl_CoordinateState_Readonly {
            get {
                return ResourceManager.GetString("ValueCopyControl_CoordinateState_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ValueCopyControl_CoordinateState_Unknown {
            get {
                return ResourceManager.GetString("ValueCopyControl_CoordinateState_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ValueCopyControl_CopyButton_Caption {
            get {
                return ResourceManager.GetString("ValueCopyControl_CopyButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy value from source.
        /// </summary>
        internal static string ValueCopyControl_CopyValueFromSource {
            get {
                return ResourceManager.GetString("ValueCopyControl_CopyValueFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery value proportional by source.
        /// </summary>
        internal static string ValueCopyControl_DeliveryValuePropotrionalSource {
            get {
                return ResourceManager.GetString("ValueCopyControl_DeliveryValuePropotrionalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver filds must not contain elements of the type &apos;All&apos;..
        /// </summary>
        internal static string ValueCopyControl_DestFieldIsAllMember {
            get {
                return ResourceManager.GetString("ValueCopyControl_DestFieldIsAllMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string ValueCopyControl_Destination {
            get {
                return ResourceManager.GetString("ValueCopyControl_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string ValueCopyControl_Dimension {
            get {
                return ResourceManager.GetString("ValueCopyControl_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        internal static string ValueCopyControl_ExportSettings_ToolTip {
            get {
                return ResourceManager.GetString("ValueCopyControl_ExportSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        internal static string ValueCopyControl_Hierarchy {
            get {
                return ResourceManager.GetString("ValueCopyControl_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Settings.
        /// </summary>
        internal static string ValueCopyControl_ImportSettings_ToolTip {
            get {
                return ResourceManager.GetString("ValueCopyControl_ImportSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run copy form.
        /// </summary>
        internal static string ValueCopyControl_RunCopyForm_Tooltip {
            get {
                return ResourceManager.GetString("ValueCopyControl_RunCopyForm_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or Receiver is selected.
        /// </summary>
        internal static string ValueCopyControl_ShowNotEmpty_Caption {
            get {
                return ResourceManager.GetString("ValueCopyControl_ShowNotEmpty_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ValueCopyControl_Source {
            get {
                return ResourceManager.GetString("ValueCopyControl_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not some field are filled in source and receiver..
        /// </summary>
        internal static string ValueCopyControl_SourceAndDestFieldNotFilled_Warning {
            get {
                return ResourceManager.GetString("ValueCopyControl_SourceAndDestFieldNotFilled_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for source and receiver must differ..
        /// </summary>
        internal static string ValueCopyControl_SourceAndDestIsEqual_Warning {
            get {
                return ResourceManager.GetString("ValueCopyControl_SourceAndDestIsEqual_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of copying:.
        /// </summary>
        internal static string ValueCopyControl_TypeOfCopying {
            get {
                return ResourceManager.GetString("ValueCopyControl_TypeOfCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        internal static string ValueCopyControl_Value {
            get {
                return ResourceManager.GetString("ValueCopyControl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сoefficient:.
        /// </summary>
        internal static string ValueCopyControl_Сoefficient {
            get {
                return ResourceManager.GetString("ValueCopyControl_Сoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copy designer.
        /// </summary>
        internal static string ValueCopyDesignerControl_Name {
            get {
                return ResourceManager.GetString("ValueCopyDesignerControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copy settings....
        /// </summary>
        internal static string ValueCopyDialog_Caption {
            get {
                return ResourceManager.GetString("ValueCopyDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children members.
        /// </summary>
        internal static string ValueDeliveryControl_ChildrenMembers {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_ChildrenMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string ValueDeliveryControl_Delivered {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell details:.
        /// </summary>
        internal static string ValueDeliveryControl_DeliveredCellSettings {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_DeliveredCellSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery to:.
        /// </summary>
        internal static string ValueDeliveryControl_DeliveryTo {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_DeliveryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        internal static string ValueDeliveryControl_Hierarchy {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string ValueDeliveryControl_Member {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members to delivery:.
        /// </summary>
        internal static string ValueDeliveryControl_MembersToDelivery {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_MembersToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        internal static string ValueDeliveryControl_NewValue {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original value.
        /// </summary>
        internal static string ValueDeliveryControl_OriginalValue {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected members.
        /// </summary>
        internal static string ValueDeliveryControl_SelectedMembers {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_SelectedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siblings members.
        /// </summary>
        internal static string ValueDeliveryControl_SiblingsMembers {
            get {
                return ResourceManager.GetString("ValueDeliveryControl_SiblingsMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value delivery settings....
        /// </summary>
        internal static string ValueDeliveryDialog_Caption {
            get {
                return ResourceManager.GetString("ValueDeliveryDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered:.
        /// </summary>
        internal static string ValueDeliveryDialog_Delivered {
            get {
                return ResourceManager.GetString("ValueDeliveryDialog_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest to delivery:.
        /// </summary>
        internal static string ValueDeliveryDialog_RestToDelivery {
            get {
                return ResourceManager.GetString("ValueDeliveryDialog_RestToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to delivery:.
        /// </summary>
        internal static string ValueDeliveryDialog_ValueToDelivery {
            get {
                return ResourceManager.GetString("ValueDeliveryDialog_ValueToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is between.
        /// </summary>
        internal static string ValueFilter_Between {
            get {
                return ResourceManager.GetString("ValueFilter_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string ValueFilter_Equal {
            get {
                return ResourceManager.GetString("ValueFilter_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string ValueFilter_Greater {
            get {
                return ResourceManager.GetString("ValueFilter_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string ValueFilter_GreaterOrEqual {
            get {
                return ResourceManager.GetString("ValueFilter_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string ValueFilter_Less {
            get {
                return ResourceManager.GetString("ValueFilter_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string ValueFilter_LessOrEqual {
            get {
                return ResourceManager.GetString("ValueFilter_LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Filter.
        /// </summary>
        internal static string ValueFilter_Name {
            get {
                return ResourceManager.GetString("ValueFilter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not between.
        /// </summary>
        internal static string ValueFilter_NotBetween {
            get {
                return ResourceManager.GetString("ValueFilter_NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not equal.
        /// </summary>
        internal static string ValueFilter_NotEqual {
            get {
                return ResourceManager.GetString("ValueFilter_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
