// Autogenerated file
using System.Reflection;

#pragma warning disable 0436
[assembly: AssemblyProduct(ProductInfo.AssemblyProduct)]
[assembly: AssemblyCopyright(ProductInfo.AssemblyCopyright)]
[assembly: AssemblyTrademark(ProductInfo.AssemblyTrademark)]
[assembly: AssemblyCompany(ProductInfo.AssemblyCompany)]
[assembly: AssemblyVersion(ProductInfo.AssemblyVersion)]
[assembly: AssemblyFileVersion(ProductInfo.AssemblyFileVersion)]

partial class ProductInfo
{
	public const string AssemblyProduct = "Ranet.UILibrary.Olap";
	public const string AssemblyCopyright = "Copyright (C) 2009 Galaktika Corporation ZAO";
	public const string AssemblyTrademark = "Ranet";
	public const string AssemblyCompany = "Galaktika";
	public const string AssemblyFileVersion = "1.0.10000.0";
	public const string AssemblyVersion = "1.0.0.0";
	public const string MajorMinorVersion = "1.0";
}
#pragma warning restore 0436
